type Data = {
  [key: string]: { title: string; score: number }[];
};

const data: Data = {
  "2006": [
    { title: "死亡笔记", score: 8.4 },
    { title: "Fate/stay night", score: 7.1 },
    { title: "零之使魔", score: 7 },
    { title: "NANA", score: 8 },
    { title: "×××HOLiC", score: 7.8 },
    { title: "樱兰高校男公关部", score: 7.6 },
    { title: "变身!偶像公主", score: 9.9 },
    { title: "翼·年代记 第二季", score: 9.9 },
    { title: "偶像宣言", score: 9.9 },
    { title: "蔷薇少女序曲", score: 9.9 },
    { title: "金色琴弦", score: 9.9 },
    { title: "完美小姐进化论", score: 9.9 },
  ],
  "2007": [
    { title: "交响情人梦", score: 9.9 },
    { title: "CLANNAD", score: 8.3 },
    { title: "小女神花铃", score: 9.9 },
    { title: "日在校园", score: 6.3 },
    { title: "暗夜魔法使", score: 9.9 },
    { title: "灼眼的夏娜", score: 9.9 },
    { title: "守护甜心", score: 9.9 },
    { title: "初音岛", score: 9.9 },
    { title: "秒速5厘米", score: 9.9 },
    { title: "口袋妖怪钻石珍珠", score: 9.9 },
    { title: "出租魔法使", score: 9.9 },
    { title: "恋爱情结", score: 9.9 },
  ],
  "2008": [
    { title: "下一站巨星", score: 9 },
    { title: "龙与虎", score: 8 },
    { title: "甜甜起司猫", score: 9.9 },
    { title: "狼与香辛料", score: 7.8 },
    { title: "超时空要塞F", score: 9.9 },
    { title: "我的狐仙女友", score: 6.1 },
    { title: "吸血鬼骑士", score: 9.9 },
    { title: "黑执事", score: 7 },
    { title: "图书馆战争", score: 9.9 },
    { title: "强袭魔女", score: 7.1 },
    { title: "SA特优生", score: 9.9 },
    { title: "伯爵与妖精", score: 9.9 },
  ],
  "2009": [
    { title: "轻音少女", score: 8.2 },
    { title: "宝石宠物", score: 9 },
    { title: "圣痕炼金士", score: 9 },
    { title: "极上!!超人气委员长", score: 9.9 },
    { title: "天降之物", score: 7.3 },
    { title: "公主恋人", score: 9.9 },
    { title: "白色相簿", score: 7.3 },
    { title: "信蜂", score: 9.9 },
    { title: "好想告诉你", score: 7.6 },
    { title: "梦色蛋糕师", score: 9.9 },
    { title: "小鸠", score: 9.9 },
    { title: "天国少女", score: 9.9 },
  ],
  "2010": [
    { title: "花丸幼稚园", score: 9.9 },
    { title: "猫耳属性", score: 9 },
    { title: "宝石宠物Tinkle☆", score: 9 },
    { title: "缘之空", score: 6.6 },
    { title: "笨蛋，测验，召唤兽", score: 7.4 },
    { title: "变身!偶像公主", score: 9.9 },
    { title: "MM一族", score: 9 },
    { title: "只有神知道的世界", score: 7.2 },
    { title: "迷途猫", score: 9.9 },
    { title: "星座彼氏starry☆sky", score: 9 },
    { title: "无法逃离的背叛", score: 9.9 },
    { title: "会长是女仆大人！", score: 6.9 },
  ],
  "2011": [
    { title: "露蒂的玩具", score: 9 },
    { title: "歌之王子殿下", score: 9.9 },
    { title: "魔法少女小圆", score: 8.6 },
    { title: "回转企鹅罐", score: 8 },
    { title: "摇曳百合", score: 7.6 },
    { title: "宝石宠物Sunshine", score: 9 },
    { title: "绯弹的亚里亚", score: 7.5 },
    { title: "无限斯特拉托斯", score: 9.9 },
    { title: "世界第一初恋", score: 6.8 },
    { title: "电波女与青春男", score: 7.1 },
    { title: "这个是僵尸吗？", score: 6.8 },
    { title: "神的记事本", score: 6.7 },
  ],
  "2012": [
    { title: "宝石宠物Kira☆Deco!", score: 9 },
    { title: "妖狐×仆SS", score: 9.9 },
    { title: "心理测量者", score: 7.9 },
    { title: "白熊咖啡厅", score: 9.9 },
    { title: "偶像活动 第一季", score: 9.9 },
    { title: "只要你说你爱我", score: 9.9 },
    { title: "K", score: 9.9 },
    { title: "潜行吧！奈亚子", score: 7 },
    { title: "邻座的怪同学", score: 7.2 },
    { title: "T宝的悲惨日常", score: 9.9 },
    { title: "元气少女缘结神", score: 9.9 },
    { title: "黑子的篮球", score: 9.9 },
  ],
  "2013": [
    { title: "进击的巨人", score: 8.2 },
    { title: "八犬传 东方八犬异闻", score: 9.9 },
    { title: "约会大作战", score: 6.6 },
    { title: "狗与剪刀的正确用法", score: 9.9 },
    { title: "我不受欢迎，怎么想都是你们的错！", score: 6.9 },
    { title: "Free!", score: 9.9 },
    { title: "FANTASISTA DOLL", score: 9.9 },
    { title: "魔法少女☆伊莉雅", score: 6.9 },
    { title: "有顶天家族", score: 9.9 },
    { title: "弹丸论破 希望学园与绝望高中生", score: 6.6 },
    { title: "黄金拼图", score: 7.3 },
    { title: "口袋妖怪XY", score: 9.9 },
  ],
  "2014": [
    { title: "宝石宠物Lady", score: 9 },
    { title: "信长协奏曲", score: 8 },
    { title: "LOVE STAGE!!", score: 7.5 },
    { title: "愚者信长", score: 9.9 },
    { title: "月刊少女野崎君", score: 7.8 },
    { title: "狼少女与黑王子", score: 9.9 },
    { title: "斩·赤红之瞳！", score: 6.6 },
    { title: "目隐都市的演绎者", score: 9.9 },
    { title: "东京喰种", score: 6.7 },
    { title: "青春之旅", score: 9.9 },
    { title: "拂晓的尤娜", score: 9.9 },
    { title: "我家浴缸的二三事", score: 9.9 },
  ],
  "2015": [
    { title: "全部变成F", score: 9.9 },
    { title: "暗杀教室", score: 7.3 },
    { title: "一拳超人", score: 8 },
    { title: "食戟之灵", score: 9.9 },
    { title: "SHOW BY ROCK!!", score: 9.9 },
    { title: "OVERLORD", score: 6.9 },
    { title: "青年黑杰克", score: 9.9 },
    { title: "赤发白雪姬", score: 7 },
    { title: "吹响！上低音号", score: 9.9 },
    { title: "黑街", score: 9.9 },
    { title: "科学小飞侠Crowds insight", score: 9.9 },
    { title: "没有黄段子存在的无聊世界", score: 6.1 },
  ],
  "2016": [
    { title: "疾走王子", score: 9.9 },
    { title: "逆转裁判", score: 9.9 },
    { title: "ReLIFE", score: 7.7 },
    { title: "超时空要塞Δ", score: 9.9 },
    { title: "Re：从零开始的异世界生活", score: 7.4 },
    { title: "文豪野犬", score: 9.9 },
    { title: "初恋Monster", score: 9.9 },
    { title: "我太受欢迎了该怎么办", score: 7.5 },
    { title: "在下坂本，有何贵干？", score: 6.5 },
    { title: "亚人", score: 7.3 },
    { title: "甲铁城的卡巴内利", score: 5.9 },
    { title: "冰上的尤里", score: 9.9 },
  ],
  "2017": [
    { title: "狂赌之渊", score: 7 },
    { title: "月色真美", score: 7.9 },
    { title: "小魔女学园", score: 7.7 },
    { title: "人渣的本愿", score: 6.6 },
    { title: "恋爱暴君", score: 9.9 },
    { title: "徒然喜欢你", score: 7.1 },
    { title: "独占我的英雄", score: 9.9 },
    { title: "舞动青春", score: 9.9 },
    { title: "宝石之国", score: 9.9 },
    { title: "魔法使的新娘", score: 9.9 },
    { title: "卫宫家今天的饭", score: 9.9 },
    { title: "假面noise", score: 9.9 },
  ],
  "2018": [
    { title: "女神异闻录5", score: 8.2 },
    { title: "紫罗兰永恒花园", score: 7.5 },
    { title: "强风吹拂", score: 8.3 },
    { title: "宅男腐女恋爱真难", score: 7.5 },
    { title: "佐贺偶像是传奇", score: 7.8 },
    { title: "博多豚骨拉面", score: 7.4 },
    { title: "哥布林杀手", score: 6.7 },
    { title: "终将成为你", score: 7.8 },
    { title: "恋如雨止", score: 7.5 },
    { title: "后街女孩", score: 6.6 },
    { title: "pop子和pipi美的日常", score: 9.9 },
    { title: "魔卡少女樱 透明牌篇", score: 9.9 },
  ],
  "2019": [
    { title: "辉夜大小姐想让我告白～天才们的恋爱头脑战～", score: 7.8 },
    { title: "鬼灭之刃", score: 7.3 },
    { title: "炎炎消防队", score: 6.5 },
    { title: "慎重勇者 ～这个勇者明明超强却过分慎重～", score: 6.9 },
    { title: "五等分的新娘", score: 6 },
    { title: "约定的梦幻岛", score: 7.6 },
    { title: "Fate/Grand Order -绝对魔兽战线巴比伦尼亚-", score: 6.8 },
    { title: "君主·埃尔梅罗二世事件簿 魔眼收集列车 Grace note", score: 6.7 },
    { title: "多罗罗", score: 9.9 },
    { title: "明治东京恋伽", score: 9.9 },
    { title: "皿三味", score: 9.9 },
    { title: "一弦定音！", score: 9.9 },
  ],
  "2020": [
    { title: "魔女之旅", score: 7.1 },
    { title: "异度侵入", score: 7.5 },
    { title: "别对映像研出手！", score: 8.1 },
    { title: "咒术回战", score: 7.1 },
    { title: "总之就是非常可爱", score: 6.3 },
    { title: "隐瞒之事", score: 7.7 },
    { title: "虚构推理", score: 6.3 },
    { title: "在魔王城说晚安", score: 7 },
    { title: "神推偶像登上武道馆我就死而无憾", score: 9.9 },
    { title: "地缚少年花子君", score: 9.9 },
    { title: "因为太怕痛就全点防御力了", score: 9.9 },
    { title: "辣妹与恐龙", score: 9.9 },
  ],
  "2021": [
    { title: "无职转生～", score: 7.9 },
    { title: "奇巧计程车", score: 8.5 },
    { title: "堀与宫村", score: 6.8 },
    { title: "天空侵犯", score: 6.3 },
    { title: "这爱情有点奇怪", score: 7 },
    { title: "圣女的魔力无所不能", score: 6.8 },
    { title: "阴晴不定大哥哥", score: 6.4 },
    { title: "工作细胞BLACK", score: 6.3 },
    { title: "异世界迷宫黑心企业", score: 6.7 },
    { title: "龙先生，想要买个家", score: 6.3 },
    { title: "Vivy萤石眼之歌", score: 6.3 },
    { title: "歌剧少女!!", score: 6.3 },
  ],
  "2022": [
    { title: "孤独摇滚！", score: 8.4 },
    { title: "莉可丽丝", score: 6.3 },
    { title: "明日方舟 黎明前奏", score: 6.3 },
    { title: "夏日重现", score: 7.5 },
    { title: "杀爱", score: 6.3 },
    { title: "更衣人偶坠入爱河", score: 7.2 },
    { title: "派对浪客诸葛孔明", score: 6.3 },
    { title: "间谍过家家", score: 7.2 },
    { title: "书虫公主", score: 6.3 },
    { title: "死神 千年血战篇", score: 6.3 },
    { title: "赛博朋克 边缘行者", score: 6.3 },
    { title: "浪漫杀手", score: 6.3 },
  ],
  "2023": [
    { title: "葬送的芙莉莲", score: 8.5 },
    { title: "药屋少女的呢喃", score: 7.5 },
    { title: "银砂糖师与黑妖精", score: 6.3 },
    { title: "我的幸福婚姻", score: 6.3 },
    { title: "和山田进行Lv999的恋爱", score: 6.3 },
    { title: "新上司是天然呆", score: 6.3 },
    { title: "跃动青春", score: 7.7 },
    { title: "宝可梦 地平线", score: 7.5 },
    { title: "白圣女与黑牧师", score: 6.3 },
    { title: "大奥", score: 6.3 },
    { title: "不死少女 杀人笑剧", score: 6.3 },
    { title: "天国大魔境", score: 7.8 },
  ],
  "2024": [
    { title: "真的要结婚吗", score: 8 },
    { title: "魔法少女与恶曾是敌人", score: 6.3 },
    { title: "轮回七次的反派千金在前敌国享受随心所欲的新婚生活", score: 6.3 },
    { title: "迷宫饭", score: 7.8 },
    { title: "防风铃", score: 6.3 },
    { title: "梦想成为魔法少女", score: 7 },
    { title: "恋语轻唱", score: 6.3 },
    { title: "地。 ―关于地球的运动―", score: 6.2 },
    { title: "失忆投捕", score: 7.9 },
    { title: "擅长逃跑的殿下", score: 6.3 },
    { title: "悲喜渔生", score: 7.3 },
    { title: "唯愿来世不相识", score: 6.3 },
  ],
};

export default data;
